### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by ronething** [KeKe-Li/data-structures-questions#314]
https://github.com/KeKe-Li/data-structures-questions/blob/master/src/chapter05/golang.01.md

501 line
> 另一种情况是P所分配的任务G很快就执行完了（分配不均），这就导致了这个处理器P很忙，但是其他的P还有任务，此时如果global runqueue没有任务G了，那么P不得不从其他的P里拿一些G来执行。

"这就导致了这个处理器P很忙"，这里指的是 P 已经将 G 执行完成了，所以是忙还是闲，还望得到您的回复，谢谢

**Comment by KeKe-Li** [comment]
这感谢提醒,这里应该是手误,这里是这个P就处于空闲状态了.已经更新谢谢.
