### ISSUE TITLE
10.Redis事物的了解CheckAndSet操作实现乐观锁 - 回答中 涉及"回滚" 部分描述有误？

### ISSUE THREAD

**Issue by LydiaCai1203** [KeKe-Li/data-structures-questions#476]
回答中说到 Redis 会进行回滚？？[官方文档](https://redis.io/topics/transactions)上说的是 Redis 是不支持回滚的。如果在事务中的某条命令发生错误，Redis 会继续把剩下的命令都执行完，保证原子性，但是，Redis 的数据不会回到事务执行之前的了。

另外回答中还说到一点，把 DISCARD 看作关系数据库中的 ROLLBACK，似乎也不对吧....... 关系型数据库(MySQL)中事务回滚靠的不是回滚日志么.... 也就是说 INSERT 了一条数据，回滚日志中会有一条 DELETE 命令。但是 DISCARD 是刷新事务队列，退出事务。并不能 ROLLBACK 吧。。。。。。。。。。。。

如果我疑问的部分有什么不对，欢迎大家指正... 冒昧了..

**Comment by ECUST-XX** [comment]
这部分问题其实可以考虑删掉了,文档不也是建议使用脚本代替事物吗?
> https://redis.io/topics/transactions#redis-scripting-and-transactions

**Comment by KeKe-Li** [comment]
这个其实是有点久了，我编辑删除下吧，谢谢指出错误.
