### ISSUE TITLE
关于zset的疑问

### ISSUE THREAD

**Issue by ECUST-XX** [KeKe-Li/data-structures-questions#500]
这部分内容是不是可以考虑修正下?我看源码注释是说的使用了跳表和hash表,其编码是使用了压缩链表或跳表
> https://github.com/KeKe-Li/data-structures-questions/blob/master/src/chapter05/golang.01.md#Redis%E6%9C%89%E5%BA%8F%E9%9B%86%E5%90%88zset%E5%BA%95%E5%B1%82%E6%80%8E%E4%B9%88%E5%AE%9E%E7%8E%B0%E7%9A%84

参考链接:
> https://github.com/redis/redis/blob/unstable/src/t_zset.c#L39
> http://redisbook.com/preview/object/sorted_set.html

**Comment by KeKe-Li** [comment]
好的，我看看，应该是redis源码更新了，我查看之后，更新下。
