### ISSUE TITLE
关于 defer 函数的使用，输出结果是否有问题

### ISSUE THREAD

**Issue by youngxhui** [KeKe-Li/data-structures-questions#591]
[Go中的defer函数使用下面的两种情况下结果是什么](https://github.com/KeKe-Li/data-structures-questions/blob/master/src/chapter05/golang.01.md#Go%E4%B8%AD%E7%9A%84defer%E5%87%BD%E6%95%B0%E4%BD%BF%E7%94%A8%E4%B8%8B%E9%9D%A2%E7%9A%84%E4%B8%A4%E7%A7%8D%E6%83%85%E5%86%B5%E4%B8%8B%E7%BB%93%E6%9E%9C%E6%98%AF%E4%BB%80%E4%B9%88)

> Go中的defer函数使用下面的两种情况下结果是什么
我们看看下面两种defer函数的返回的是什么:
> ```go
>	a := 1
>	defer fmt.Println("the value of a1:",a)
>	a++
>
>	defer func() {
>		fmt.Println("the value of a2:",a)
>	}()
>```
>运行:
>```
> the value of a1: 1
> the value of a1: 2
>```

这里运行结果是否写错了？
运行环境 go 1.16 mac
```
the value of a2: 2
the value of a1: 1
```

**Comment by KeKe-Li** [comment]
感谢指出来，是的，应该是我编辑的时候打错了，结果是：
`
the value of a2: 2
the value of a1: 1
`
